title: "New Knowledge"
author: "Daniel TG"
description: "Una recolección de mis aprendizajes a lo largo de mis prácticas FCT de DAW."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "datregu@mail.com"
twitter_username: "da_nielet"
github_username: "datregu"
linkedin_username: "datregu"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
